In [2]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
array = np.array([4,5,6])
print(array)
list = [4,5,6]
print(list)

[4 5 6]
[4, 5, 6]


In [12]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[:,:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[0:2,0:3])


[[1 2 3]
 [5 6 7]]


In [14]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[0:,1:3])


[[ 2  3]
 [ 6  7]
 [10 11]]


In [15]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[-1:,])


[[ 9 10 11 12]]


In [16]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[-2:-1,-3:-1])


[[6 7]]


In [17]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array[0:-1,0:-1])


[[1 2 3]
 [5 6 7]]


In [14]:
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array)
print(array[0:-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
import numpy as np
a= np.array([1,2,3,4])
print(a[-1])

4


In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
print(arr+5)


[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [26]:
import numpy as np 
arr = np.array([[1,5, 12], [2,32, 20], [3, 40, 13]])
print(arr)
print(arr.max())
print(arr.max(axis = 1)) 
print(arr.max(axis = 0)) 
print (arr.min(axis = 0))
print(arr.min(axis = 1)) 
print (arr.sum( ))
print ( arr.sum(axis=0))
print( arr.sum(axis=1))


[[ 1  5 12]
 [ 2 32 20]
 [ 3 40 13]]
40
[12 32 40]
[ 3 40 20]
[ 1  5 12]
[1 2 3]
128
[ 6 77 45]
[18 54 56]


In [46]:
import numpy as np 
a = np.array([[1, 3], [3, 4]]) 
b = np.array([[4, 3], [2, 1]]) 
print (a + b) 
print (a*b) 


[[5 6]
 [5 5]]
[[4 9]
 [6 4]]


In [52]:
import numpy as np

# create numpy arrays x1 and x2
x1 = np.array([1, 3, 0, 7])
x2 = np.array([2, 0, 1, 1])
# elementwise sum with np.add()
x3 = np.add(x1, x2)
print(x3)
print("x1:", x1)
print("x2:", x2)
print("x3:", x3)


[3 3 1 8]
x1: [1 3 0 7]
x2: [2 0 1 1]
x3: [3 3 1 8]


In [4]:
import numpy as np
arr=np.full((2,2),3)
print(arr)

[[3 3]
 [3 3]]


In [6]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [8]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6], [7, 8, 9], [10, 11, 12],
[13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [12]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6], [7, 8, 9], [10, 11, 12],
[13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [18]:
import numpy as np
from numpy import linalg as LA
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
w,v= LA.eig(a)
print(w)
print(v)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [20]:
import numpy as np
from numpy import random
x=random.randint(100)
print(x)

48


In [22]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 5 7 5 7 7 5 5 5 5 3 7 5 7 7 7 5 5 5 3 7 7 5 7 7 7 7 7 7 7 7 7 5 7 5 7 7
 5 5 7 7 5 7 7 3 7 7 5 3 3 7 5 7 7 7 3 7 5 3 3 7 5 5 7 5 3 7 7 5 7 7 5 3 5
 7 7 7 5 7 7 3 5 5 7 7 7 5 7 7 5 7 5 7 7 7 7 5 7 5 7]


In [28]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
