In [1]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[1 2 3 4 5 6]


In [4]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6,7,8])
newarr = np.split(arr,4 )
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [16]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [19]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [20]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.vsplit(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6], dtype=int64),)


In [23]:
import numpy as np
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print("Rank of A:", np.linalg.matrix_rank(A))
print("\nTrace of A:", np.trace(A))
print("\nDeterminant of A:", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))


Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [25]:
import numpy as np
from numpy import linalg as LA 
A = np.array([[1,2,3],[3,2,1],[1,0,-1]]) 
w, v = LA.eig(A) 
print(w) 
print(v) 



[ 4.31662479e+00 -2.31662479e+00  2.13869201e-17]
[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


In [26]:
from numpy import random
x = random.rand()
print(x)


0.773767366716825


In [27]:
from numpy import random
x = random.randint(100)
print(x)

50


In [28]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[90 95 80 10  9]


In [7]:
from numpy import random
x = random.normal(size=(2, 3))
print(x)

[[ 1.24919191 -0.74322038  0.07210927]
 [-0.85840292 -1.6470116   0.2518118 ]]


In [1]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 7 7 7 5 7 5 3 5 7 7 7 7 7 3 7 7 5 7 7 5 5 3 5 7 5 5 7 7 7 7 7 5 3 7 7 7
 7 7 7 7 7 7 5 7 7 7 5 5 7 5 7 7 5 7 7 5 7 7 3 5 7 5 7 3 5 5 7 7 7 7 7 7 5
 7 7 5 7 5 7 3 3 3 7 7 7 5 7 5 7 5 7 7 5 3 7 5 7 7 7]


In [3]:
from numpy import random
x = random.chisquare(df=2, size=(2, 3))
print(x)

[[0.76943135 3.10108759 2.72588435]
 [3.38374838 1.4707513  0.26387863]]


In [5]:
from numpy import random
x = random.uniform(size=(2, 3))
print(x)

[[0.62238066 0.70567359 0.25959437]
 [0.45278904 0.44984426 0.68443827]]
